### ISSUE TITLE
Job trace page Job name Chinese garbled

### ISSUE THREAD

**Issue by jinjiangxu** [apache/shardingsphere-elasticjob-ui#109]
### Which version of ElasticJob did you use?
master branch

### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite

### Expected behavior

83901-83902-BF1A_20210226163848000_20210226164712000-通用校时数据加工

### Actual behavior
![image](https://user-images.githubusercontent.com/18750962/109280241-b807bc00-7855-11eb-873e-239df550d552.png)

**Comment by TeslaCN** [comment]
Hi @jinjiangxu 
What's your database and configurations?
I tried on my PostgreSQL and the Chinese displayed normally.
![image](https://user-images.githubusercontent.com/20503072/125181895-ee116f80-e23b-11eb-950d-84073c9ef860.png)

**Comment by TeslaCN** [comment]
Close due to no response.
