### ISSUE TITLE
Config job overwrite=true

### ISSUE THREAD

**Issue by guanziao** [apache/shardingsphere-elasticjob-ui#111]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob-ui/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ElasticJob did you use?
3.0.0-RC1
### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite
### Expected behavior
When I config the job overwrite=true in the Spring, the job configuration will be overwritten 
### Actual behavior
When I config the job overwrite=true, no Job dimension item show on the console

**Comment by TeslaCN** [comment]
Make sure you have connected to the right Zookeeper server and namespace. The jobs will be listed in the Job Dimension page.

**Comment by TeslaCN** [comment]
Close due to no response.
