### ISSUE TITLE
Registry Center can`t connect zookeeper

### ISSUE THREAD

**Issue by icuxxz** [apache/shardingsphere-elasticjob-ui#113]
### Which version of ElasticJob did you use?
apache-shardingsphere-elasticjob-3.0.0-RC1-lite-ui-bin     3.0.0-snapshot
### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite
### Expected behavior
connect with zookeeper
### Actual behavior
The connect button post param with name only. ZkAddress is useless.
### Reason analyze (If you can)
the method handleconnect in registry-center.vue 
![image](https://user-images.githubusercontent.com/46012309/114138540-5e101100-9940-11eb-885d-60975fedf345.png)
![image](https://user-images.githubusercontent.com/46012309/114138628-7d0ea300-9940-11eb-977e-c9ee38717367.png)

**Comment by TeslaCN** [comment]
Hi @Pudge-T 
I cannot reproduce your problem in my environment. Could you show me what you have typed in the page?

**Comment by lubb** [comment]
i have issue this problem
please reset maxSleepTimeMilliseconds 、baseSleepTimeMilliseconds ,don‘t use default value
private int baseSleepTimeMilliseconds = 10000;
private int maxSleepTimeMilliseconds = 30000;

**Comment by TeslaCN** [comment]
Close due to no response.
