### ISSUE TITLE
Unable to find property 'jobClass' on class: org.apache.shardingsphere.elasticjob.infra.pojo.JobConfigurationPOJO

### ISSUE THREAD

**Issue by nanjinglex** [apache/shardingsphere-elasticjob-ui#117]
![image](https://user-images.githubusercontent.com/44739893/121021613-243e7800-c7d4-11eb-8a69-e102a9ccc379.png)

**Comment by TeslaCN** [comment]
Did you use the ElasticJob 2.x before?

**Comment by BertOnline** [comment]
@TeslaCN I also found this problem，this problem occurs when I use elastic-job 3.0 and elastic-job-ui 3.0RC1, but not when I use elastic-job 3.0RC1 and elastic-job-ui 3.0RC1, error log : Unable to find property 'staticSharding' on class: org.apache.shardingsphere.elasticjob.infra.pojo.JobConfigurationPOJO

**Comment by TeslaCN** [comment]
> @TeslaCN I also found this problem，this problem occurs when I use elastic-job 3.0.0 and elastic-job-ui 3.0.0-RC1, but not when I use elastic-job 3.0.0-RC1 and elastic-job-ui 3.0.0-RC1, error log : Unable to find property 'staticSharding' on class: org.apache.shardingsphere.elasticjob.infra.pojo.JobConfigurationPOJO

@BertOnline Try the latest 3.0.0 GA.

**Comment by TeslaCN** [comment]
I'm closing this since no response from author.

**Comment by lovepoem** [comment]
When you use `elasticjob-client v3.1.0` ,  the new meta data `org.apache.shardingsphere.elasticjob.infra.pojo.JobConfigurationPOJO` will be write to zk .  But now your web console refers `elasticjob-3.0.0-SNAPSHOT`，the Exception occured.   You should use new  web console  to instead
