### ISSUE TITLE
docker打包

### ISSUE THREAD

**Issue by Yang31415926** [apache/shardingsphere-elasticjob-ui#132]
docker打包成功后, 运行报 "/bin/sh: 1: /opt/shardingsphere-elasticjob-lite-ui/bin/start.sh: not found"
打包命令:c:/projects/shardingsphere-elasticjob-ui>  clean package -Dmaven.test.skip=true  -Prelease -Pdocker

**Comment by TeslaCN** [comment]
Please check if files exist in Docker image.

**Comment by TeslaCN** [comment]
Hi @Yang31415926 
Could you try the following command?
```bash
./mvnw clean package -Dmaven.test.skip=true -Prelease,docker
```
