### ISSUE TITLE
I have multi-datasources  in the "Registry center" page,  I cannot choose others but the first one

### ISSUE THREAD

**Issue by lovepoem** [apache/shardingsphere-elasticjob-ui#136]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob-ui/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ElasticJob did you use?

![image](https://user-images.githubusercontent.com/827112/143395284-48122217-dc9b-41d6-bb65-753b1ca70d00.png)

I configure several namespaces int the in the "Registry center" page,  but I cannot choose others but the first one

**Comment by lovepoem** [comment]
http://localhost:8088/#/registry-center

**Comment by lovepoem** [comment]
![image](https://user-images.githubusercontent.com/827112/145402695-d897e027-8b4c-41f0-911b-b074b47d525e.png)
Another one found

**Comment by TeslaCN** [comment]
Hi @lovepoem 
I couldn't reproduce this issue. Is there any error logs?

**Comment by TeslaCN** [comment]
![image](https://user-images.githubusercontent.com/20503072/146667004-c82e2129-789e-4c44-bbfd-6b692ab3241e.png)

**Comment by TeslaCN** [comment]
Close due to no response.
