### ISSUE TITLE
Is the release binary package corrupted?

### ISSUE THREAD

**Issue by cocodroid** [apache/shardingsphere-elasticjob-ui#143]
https://www.apache.org/dyn/closer.cgi/shardingsphere/elasticjob-ui-3.0.0/apache-shardingsphere-elasticjob-3.0.0-lite-ui-bin.tar.gz

Download it and find out:

![20211223224214](https://user-images.githubusercontent.com/11642752/147256740-9fa26143-81a9-4762-839a-b079be669c30.jpg)

**Comment by TeslaCN** [comment]
Hi @cocodroid 
You may refer to the FAQ https://shardingsphere.apache.org/elasticjob/current/en/faq/#12-in-windows-env-run-shardingsphere-elasticjob-ui-could-not-find-or-load-main-class-orgapacheshardingsphereelasticjobliteuibootstrap-why

**Comment by cocodroid** [comment]
@TeslaCN thank you!
