### ISSUE TITLE
help, start by jar for shardingsphere-elasticjob-lite-ui-backend and tips There is no main manifest attribute in the jar.

### ISSUE THREAD

**Issue by Summary-wcj** [apache/shardingsphere-elasticjob-ui#146]
I download shardingsphere-elasticjob-lite-ui locally,and i can shardingsphere-elasticjob-lite-ui-frontend and shardingsphere-elasticjob-lite-ui-backend Separate start locally, but when I package  shardingsphere-elasticjob-lite-ui-backend into jar and start using jar ,then tips 
shardingsphere-elasticjob-lite-ui.jar  There is no main manifest attribute in the jar. for this what do I need to do .

Or it is wrong to start by jar

我在本地下载shardingsphere elasticjob lite ui，我可以在本地单独启动shardingsphere elasticjob lite ui前端和shardingsphere elasticjob lite ui后端，但当我将shardingsphere elasticjob lite ui后端打包到jar并开始使用jar时，提示

shardingsphere elasticjob lite用户界面。jar中没有主清单属性。为此，我需要做些什么。

或者从jar开始是错误的

**Comment by sunkai-cai** [comment]
https://github.com/apache/shardingsphere-elasticjob-ui/blob/master/README_ZH.md
