### ISSUE TITLE
注册中心配置超过两页不展示

### ISSUE THREAD

**Issue by createPg** [apache/shardingsphere-elasticjob-ui#152]
分页异常,注册中心配置超过两页不展示;
![图片](https://user-images.githubusercontent.com/24729992/161226063-b0105462-e968-4ef5-a4ee-e4932f16fd30.png)

**Comment by JiangAudit** [comment]
我这样也发现了这个问题，都搁置了2个星期了

**Comment by BertOnline** [comment]
同样的问题
