### ISSUE TITLE
Could not find or load the main class

### ISSUE THREAD

**Issue by mitht** [apache/shardingsphere-elasticjob-ui#37]
解压缩后运行bin/start.sh；

nohup: ignoring input
错误: 找不到或无法加载主类 org.apache.shardingsphere.elasticjob.lite.ui.Bootstrap

**Comment by menghaoranss** [comment]
@mitht Which OS do you use，if it's windows, please run bin/start.bat , linux or mac os please run bin/start.sh

**Comment by terrymanu** [comment]
I will release `elasticjob-ui-3.0.0-alpha` tomorrow if no response.

**Comment by menghaoranss** [comment]
@mitht We could not reproduce your problem in mac os and windows, and now we will release `elasticjob-ui-3.0.0-alpha`, this issue will be closed soon.

**Comment by TheheiWorld** [comment]
the same problem 
version: 3.0.0-alpha

Starting the ShardingSphere-ElasticJob-UI ...
错误: 找不到或无法加载主类 org.apache.shardingsphere.elasticjob.lite.ui.Bootstrap
请按任意键继续. . .
