### ISSUE TITLE
Extract rat plugin config to root pom file in shardingsphere-elasticjob-ui

### ISSUE THREAD

**Issue by kimmking** [apache/shardingsphere-elasticjob-ui#42]
Extract rat plugin config to root pom file in shardingsphere-elasticjob-ui.
Now rat config in several sub module pom files.

Refer: https://github.com/apache/shardingsphere-ui/blob/master/pom.xml

**Comment by kimmking** [comment]
hi @cowcomic , your pr #41 add rat to root pom, and the rat in sub projects should be removed, you can submit a new PR to remote them.

**Comment by cowcomic** [comment]
> hi @cowcomic , your pr #41 add rat to root pom, and the rat in sub projects should be removed, you can submit a new PR to remote them.

OK

**Comment by cowcomic** [comment]
https://github.com/apache/shardingsphere-elasticjob-ui/pull/43
