### ISSUE TITLE
事件追踪数据源 不支持mysql吗

### ISSUE THREAD

**Issue by TheheiWorld** [apache/shardingsphere-elasticjob-ui#46]
配置参数
{
    "name":"mysql",
    "driver":"com.mysql.cj.jdbc.Driver",
    "url":"jdbc:mysql://localhost:3306/elastic_job",
    "username":"root",
    "password":"admin"
}
显示没有 java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver 这个驱动
是需要自己开发吗

**Comment by TeslaCN** [comment]
Put driver JAR to lib by yourself.

**Comment by terrymanu** [comment]
For english only
