### ISSUE TITLE
After building , release package shardingsphere-elasticjob-lite-ui-bin.tar.gz  cannot be found

### ISSUE THREAD

**Issue by lovepoem** [apache/shardingsphere-elasticjob-ui#60]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob-ui/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/). 

### Which version of ElasticJob did you use?

3.0
### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?

ElasticJob-Lite

### Expected behavior

As presented in README.md,
```
Get the lite tar in shardingsphere-elasticjob-ui/shardingsphere-elasticjob-ui-distribution/shardingsphere-elasticjob-lite-ui-bin-distribution/target/apache-shardingsphere-${latest.release.version}-shardingsphere-elasticjob-lite-ui-bin.tar.gz
```
the  tar package can be generated

### Actual behavior
Now I cannot find it 

### Reason analyze (If you can)
CI issue

**Comment by TeslaCN** [comment]
Did you add argument '-Prelease'?

**Comment by lovepoem** [comment]
> Did you add argument '-Prelease'?

Now I get the release packages following :

1、Install puppeteer
```log
[ERROR] ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
[ERROR] { Error: read ETIMEDOUT
[ERROR]     at _errnoException (util.js:1022:11)
[ERROR]     at TLSWrap.onread (net.js:628:25)
[ERROR]   -- ASYNC --

```

```
npm config set puppeteer_download_host=https://npm.taobao.org/mirrors
npm i puppeteer
```


2、Build thee release package 

`mvn clean install -Dmaven.test.skip -Prelease `

Now it is success
