### ISSUE TITLE
mvn clean package -Prelease error

### ISSUE THREAD

**Issue by wjce** [apache/shardingsphere-elasticjob-ui#61]
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm run rimraf) on project shardingsphere-elasticjob-lite-ui-frontend: Failed to run task: 'npm run rim
raf' failed. java.io.IOException: Cannot run program "E:\education\shardingsphere-elasticjob-ui-master\shardingsphere-elasticjob-lite-ui\shardingsphere-elasticjob-lite-ui-frontend\node\
node.exe" (in directory "E:\education\shardingsphere-elasticjob-ui-master\shardingsphere-elasticjob-lite-ui\shardingsphere-elasticjob-lite-ui-frontend"): CreateProcess error=193, %1 不
是有效的 Win32 应用程序

**Comment by yu199195** [comment]
you can use cnpm(The mirror of alibaba taobao)  to download the dependent package.

**Comment by kimmking** [comment]
mvn clean package -Prelease, node-cn
