### ISSUE TITLE
Use the existed gson object instead of creating a new one

### ISSUE THREAD

**Issue by Technoboy-** [apache/shardingsphere-elasticjob-ui#72]
Two class need to update:
1.  https://github.com/apache/shardingsphere-elasticjob-ui/blob/7b53e470dc36f6049a926e07f155224ccdcab9cf/shardingsphere-elasticjob-cloud-ui/shardingsphere-elasticjob-cloud-ui-backend/src/main/java/org/apache/shardingsphere/elasticjob/cloud/ui/security/AuthenticationFilter.java#L97
2. https://github.com/apache/shardingsphere-elasticjob-ui/blob/7b53e470dc36f6049a926e07f155224ccdcab9cf/shardingsphere-elasticjob-lite-ui/shardingsphere-elasticjob-lite-ui-backend/src/main/java/org/apache/shardingsphere/elasticjob/lite/ui/security/AuthenticationFilter.java#L97

**Comment by gzdzss** [comment]
assign to me.
