### ISSUE TITLE
JobConfigController#getJobConfig PathVariable bug

### ISSUE THREAD

**Issue by jackycchen** [apache/shardingsphere-elasticjob-ui#74]
### Which version of ElasticJob did you use?
the lastest source code 3.0.0-alpha

### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite

### Expected behavior
input: the jobName contains dot, e.g. **myjob.sync.query.job**
the uri = api/jobs/config/myjob.sync.query.job
jobName= myjob.sync.query.job

### Actual behavior
jobName= myjob.sync.query

### Reason analyze (If you can)
the last.job will be truncated by spring mvc, just like the familiar suffix — **.do**

### Solution
the correct code is : @GetMapping(value = "/{jobName:.+}")

**Comment by TeslaCN** [comment]
You may submit a PR if you are interested in.

**Comment by jackycchen** [comment]
ok
