### ISSUE TITLE
Add conf/auth.properties to modify the account that to login but it didn't work...

### ISSUE THREAD

**Issue by CropCollector** [apache/shardingsphere-elasticjob-ui#80]
Read the document [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

It said that change the conf/auth.properties to modify the account. but i didn't find the file under the dir, so i add the file and change the password.

Then i restart the project but the change didn't work...

It that what i made mistakes?

**Comment by TeslaCN** [comment]
You may configure auth in `application.properties`. The documents are outdate. You may submit a PR to update the documents if you are interested in our project, or we will update it later.

```
auth.root_username=root
auth.root_password=root
auth.guest_username=guest
auth.guest_password=guest
```

**Comment by CropCollector** [comment]
> You may configure auth in `application.properties`. The documents are outdate. You may submit a PR to update the documents if you are interested in our project, or we will update it later.
> 
> ```
> auth.root_username=root
> auth.root_password=root
> auth.guest_username=guest
> auth.guest_password=guest
> ```

thx, it works. And I submitted a PR in the project elasticjob.

**Comment by TeslaCN** [comment]
Thanks for you participation! This issue has been fixed by https://github.com/apache/shardingsphere-elasticjob/pull/1785
